#ifndef KURSACH_KEYBOARDBUTTON_H
#define KURSACH_KEYBOARDBUTTON_H

enum KeyboardButton {
    ARROW_LEFT = 75,
    ARROW_RIGHT = 77,
    ARROW_UP = 72,
    ARROW_DOWN = 80,
    ENTER = 13,
    ESC = 27
};

#endif //KURSACH_KEYBOARDBUTTON_H
